name: first-action
on: [push]
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: npm-version
        run: |
          npm -v
          node -v
          npm install sfdx-cli --global
          npm install @salesforce/cli --global
          sfdx -v