name: actions-example
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simples js action
      id: greet
      uses: EmilyADS/hello-world-javascript-action
      with:
        who-to-greet: emily
      - name: logando
        run: echo "{{ steps.greet.outputs.time }}"