name: actions-example
# on: [push]
on: 
  repository_dispatch:
    types: [build]
  # push:
  pull_request:
    types: [closed, opened, reopened]
  #schedule:
  #  -cron: "* * * * *"
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: variáveis de ambiente do github
        run: |
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
      - name: simples js action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: emily
      - name: logando
        run: echo "${{ steps.greet.outputs.time }}"