name: actions-example

on:
  pull_request_review:
    types: [edited]
  # push:
    # branchs:
    #  - main
    #  -'!develop'
  # pull_request:
  #   types: [closed, opened, reopened]
  #schedule:
  #  -cron: "* * * * *"
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: paylod via postman pegando a env
        run: |
          echo ${{ github.event.client_payload.env}}
      - name: variáveis de ambiente do github
        run: |
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
      - name: simples js action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: emily
      - name: logando
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        