name: create-version
on:

  push
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    outputs:
      only_promote: ${{ steps.step_pr.outputs.only_promote }}
    steps:
    - name: checkout - para ler o repo atual
      uses: actions/checkout@v1

    - name: teste leitura de arquivo
      run: |
        pwd
        ls
        jq -s '.mywork[].sfdx-project.packageDirectories[].dependencies' > list.json
        ls
        cat list.json

    - name: write without show
      run: |
        echo "antes"
        > file1.txt cat <<< "This is a here-string with random"         
        echo "depois"
        cat file1.txt 
        gmud=

        echo "GMUD=comvalor" >> .env
        cat .env >> $GITHUB_ENV
        cat $GITHUB_ENV
    - name: nao-pega-env-do-mesmo-step
      id: step_pr
      run: |  
        echo "[DEBUG] ${{ env.GMUD }} "
        # if [[ -z $gmud ]]; then
        if [[ -z "${{ env.GMUD }}" ]]; then
          echo "gmud vazia"
          echo "only_promote=true" >> $GITHUB_OUTPUT
        else
          echo "gmud com valor"
          echo "only_promote=false" >> $GITHUB_OUTPUT
        fi
        cat $GITHUB_OUTPUT

  mostrando-info:
    runs-on: ubuntu-latest
    needs: [runs-shell-commands]
    steps:
    - name: printando-saida
      run: |
        echo ${{ needs.runs-shell-commands.outputs.only_promote }}

        if [[ ${{ needs.runs-shell-commands.outputs.only_promote }} == 'false' ]]; then
          echo "bate valores"
        else
          echo "lascou"
        fi

  runs-second-job:
    needs: [runs-shell-commands]
    if: needs.runs-shell-commands.outputs.only_promote == 'false'
    runs-on: ubuntu-latest
    steps:
    - name: npm-version
      run: |
        echo ${{ needs.runs-shell-commands.outputs.only_promote }}
        npm -v
        node -v
        npm install sfdx-cli --global
        npm install @salesforce/cli --global
        sfdx -v
    - name: chekout - para ler o repo atual
      uses: actions/checkout@v1
    - name: List files - pra ver se clona mesmo na maquina local
      run: |
        pwd
        ls
    - name: connected app - DECRYPTED
      run: |
        openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
    - name: connected app - authorize2
      run: |
        echo username value ${{ secrets.USERNAME_STAGING }}
        sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY }} --username=${{ secrets.USERNAME }} --jwtkeyfile server.key --instanceurl https://testeemily1-dev-ed.my.salesforce.com

        sfdx force:package:version:create -d TESTE-App -k password123
