name: create-version
on:

  push
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    outputs:
      info_gmud: ${{ steps.step_pr.outputs.only_promote }}
    steps:
    - name: write without show
      id: step_pr
      run: |
        echo "antes"
        > file1.txt cat <<< "This is a here-string with random"         
        echo "depois"
        cat file1.txt 
        gmud=gm54545
        if [[ -z $gmud ]]; then
          echo "only_promote=true" >> GITHUB_OUTPUT
        else
          echo "only_promote=false" >> GITHUB_OUTPUT
        fi


  runs-second-job:
    runs-on: ubuntu-latest
    needs: [runs-shell-commands]
    if: needs.runs-shell-commands.outputs.info_gmud == 'true'
    steps:
    - name: npm-version
      run: |
        npm -v
        node -v
        npm install sfdx-cli --global
        npm install @salesforce/cli --global
        sfdx -v
    - name: chekout - para ler o repo atual
      uses: actions/checkout@v1
    - name: List files - pra ver se clona mesmo na maquina local
      run: |
        pwd
        ls
    - name: connected app - DECRYPTED
      run: |
        openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
    - name: connected app - authorize2
      run: |
        echo username value ${{ secrets.USERNAME_STAGING }}
        sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY }} --username=${{ secrets.USERNAME }} --jwtkeyfile server.key --instanceurl https://testeemily1-dev-ed.my.salesforce.com

        sfdx force:package:version:create -d TESTE-App -k password123
