name: create-version
on: [push]
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: npm-version
        run: |
          npm -v
          node -v
          npm install sfdx-cli --global
          npm install @salesforce/cli --global
          sfdx -v
      - name: chekout - para ler o repo atual
        uses: actions/checkout@v1
      - name: List files - pra ver se clona mesmo na maquina local
        run: |
          pwd
          ls
      - name: connected app - DECRYPTED
        run: |
          openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
      - name: connected app - authorize2
        run: |
          echo username value ${{ secrets.USERNAME_STAGING }}
          sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY }} --username=${{ secrets.USERNAME }} --jwtkeyfile server.key --instanceurl https://testeemily1-dev-ed.my.salesforce.com

          sfdx force:package:version:create -d TESTE-App -k password123
