name: testes-migracao-pipeline
on:
  push
jobs:
  github-testes-migracao-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Alterando timestamp gmud e efetuando sleep
        run: |
          echo -e "#### Convertendo para TZ America/Sao_Paulo ####";

          start_date="2022-11-07 01:00:00"
          echo -e "Data da mudança na gmud: $start_date"

          convert_to_date=$(date -d "$start_date")
          echo -e "convert_to_date --> $convert_to_date"

          brasilian_time="$(TZ=America/Sao_Paulo date -d "$convert_to_date" +'%m/%d/%Y %H:%M')"
          echo -e "brasilian_time --> $brasilian_time"

          echo -e "\n#### get seconds ####"
          convert_seconds_start_date=$(date -d "$brasilian_time" +%s)
          echo -e "convert_seconds_start_date --> $convert_seconds_start_date"

          echo -e "\n#### sleep ####"
          export TZ=America/Sao_Paulo
          date
          current_epoch=$(date +%s)
          sleep_seconds=$(($convert_seconds_start_date - $current_epoch))
          echo "sleep_seconds --> $sleep_seconds"

          echo -e "\n#### Sua Gmud dará inicio em: ####"
          eval "echo $(date -ud "@$sleep_seconds" +'$((%s/3600/24)) days %H hours %M minutes %S seconds')"

          echo -e "\n #### validando se bate o tempo- lembrando do gmt-3 ####"
          date_hour=$(($sleep_seconds + $current_epoch))
          teste=$(date -d "@$date_hour" )
          echo $teste

          sleep $sleep_seconds

