name: usando-token-github
on: [push]

jobs:
  github-token-insert-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: criando arquivo autenticado via token
        run: |
          echo "pasta atual"
          pwd
          ls -a
          echo "criando um novo repo no git"
          git init
          echo "logando no nosso repositorio via token para executar no servidor os comandos do git"
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          echo "inserindo um responsável pelo commit novo do arquivo gerado aleatoriamente"
          git config --global user.email "teste@teste.com"
          git config --global user.name "teste"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add .
          git commit -m "random file"
          git push
