name: testes-migracao-pipeline
on: [ push ]

jobs:
  github-testes-migracao-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: criando arquivo autenticado via token
        run: |
          echo -e "#### Convertendo para TZ America/Sao_Paulo ####";

          start_date="2022-10-29 01:00:00"
          echo -e "Data da mudança na gmud: $start_date"

          convert_to_date=$(date -d "$start_date")
          echo -e "convert_to_date --> $convert_to_date"

          brasilian_time="$(TZ=America/Sao_Paulo date -d "$convert_to_date" +'%m/%d/%Y %H:%M')"
          echo -e "brasilian_time --> $brasilian_time"

          echo -e "\n#### get seconds ####"
          convert_seconds_start_date=$(date -d "$brasilian_time" +%s)
          echo -e "convert_seconds_start_date --> $convert_seconds_start_date"

          echo -e "\n#### sleep ####"
          export TZ=America/Sao_Paulo
          date
          current_epoch=$(date +%s)
          sleep_seconds=$(($convert_seconds_start_date - $current_epoch))
          echo "sleep_seconds --> $sleep_seconds"

          echo -e "\n#### Sua Gmud dará inicio em: ####"
          eval "echo $(date -ud "@$sleep_seconds" +'$((%s/3600/24)) days %H hours %M minutes %S seconds')"

          # pwd
          # ls -a
          # echo "criando um novo repo no git - git init"
          # git init
          # echo "logando no nosso repositorio via token para executar no servidor os comandos do git"
          # git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          # echo "inserindo um responsável pelo commit novo do arquivo gerado aleatoriamente"
          # git config --global user.email "teste@teste.com"
          # git config --global user.name "teste"
          # echo "vendo se não tem commit pendente"
          # git fetch
          # echo "logando na branch main"
          # git checkout main
          # git branch --set-upstream-to=origin/main
          # echo "atualizando a branch atual"
          # git pull
          # echo "listando o conteúdo da branch atual"
          # ls -a
          # echo "escrevendo um arquivo txt"
          # echo $RANDOM >> random.txt
          # echo "listando os arquivos da branch atual"
          # ls -a
          # echo "commitando e dando push"
          # git add .
          # git commit -m "random file"
          # git push
