name: first-action
on: [push]
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: python commands
        run: |
          print("Hello World")
          test = "123"
          print(test)
          if "1" in test:
            print("hello")
          else:
            print("bye")
        shell: python
      - name: npm-version
        run: |
          npm -v
          node -v
          npm install sfdx-cli --global
          npm install @salesforce/cli --global
          sfdx -v
      - name: connected app
        run: |
          sfdx auth:jwt:grant --clientid 3MVG9dZJodJWITSsG.BrFRTEjksR1pjSwekGx1.Mnqx.t8XPdk4wvPbCoJyXAsJwlIHoRuEiWxcr0JVMpDPJz --jwtkeyfile /Users/emily/Documents/ssl/server.key --username emily.berteloni@companyteste1.com --instanceurl https://testeemily1-dev-ed.my.salesforce.com
        shell: sh
      
