name: first-action
on: [push]
jobs:
  runs-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: python commands
        run: |
          print("Hello World")
          test = "123"
          print(test)
          if "1" in test:
            print("hello")
          else:
            print("bye")
        shell: python
      - name: npm-version
        run: |
          npm -v
          node -v
          npm install sfdx-cli --global
          npm install @salesforce/cli --global
          sfdx -v
      
